DECLARE sql_stmt long;
BEGIN sql_stmt := 'CREATE TABLE vehicle (id NUMBER PRIMARY KEY, name VARCHAR(16) UNIQUE)';
EXECUTE IMMEDIATE sql_stmt;
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL;
ELSE RAISE;
END IF;
END; ;;