apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-db
  labels:
    app.kubernetes.io/part-of: vehicle-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: vehicle-db
  name: vehicle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: vehicle-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: vehicle-db
    spec:
      initContainers:
      - name: remove-lost-found
        image: busybox
        command:
        - sh
        - -c
        - |
          rm -fr /opt/oracle/oradata/lost+found
          # oracle user, oinstall group
          chown -R 54321:54321 /opt/oracle/oradata
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: vehicle-db
          mountPath: /opt/oracle/oradata
      containers:
      - env:
        - name: ORACLE_RANDOM_PASSWORD
          value: "true"
        - name: ORACLE_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: vehicle-db
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: vehicle-db
        - name: APP_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: vehicle-db
        image: gvenzl/oracle-xe:21-slim
        startupProbe:
          exec:
            command: [ "/opt/oracle/healthcheck.sh" ]
        name: oracle
        ports:
        - containerPort: 1521
          name: vehicle-db
          protocol: TCP
        volumeMounts:
        - name: vehicle-db
          mountPath: /opt/oracle/oradata
      volumes:
      - name: vehicle-db
        persistentVolumeClaim:
          claimName: vehicle-db
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-db
spec:
  ports:
  - port: 1521
  selector:
    app.kubernetes.io/part-of: vehicle-db
---
apiVersion: v1
kind: Secret
metadata:
  name: vehicle-db
type: servicebinding.io/oracle
stringData:
  type: oracle
  jdbc-url: jdbc:oracle:thin:@//vehicle-db:1521/vehicle
  username: vehicle
  password: vehicle
  database: vehicle